database:
    user_name: real_time_slide_share
    user_password: WOMy(iB(3.D3!pv0
    host: localhost
    port: 3306
    db_name: real_time_slide_share
env:
    api_docs: true
    allow_cors: true
    cors_allow_origins: ["http://localhost:5173"]
    root_path: /rtss/api
restriction: #必要に応じてDBの再生成が必要
    max_page: 50 #単位:ページ SmallInt最大:32767
    max_file_size: 52428800 #単位:バイト 1024x1024x50=52428800=50MB
    max_single_file_size: 1048576 #単位:バイト 1024x1024=1048576=1MB
    max_title_length: 32 #単位:文字
    db_uuid_length: 16 #単位:文字 uuid関数最大:32
    presentation_id_length: 16 #単位:文字 uuid関数最大:32
    session_id_length: 32 #単位:文字 uuid関数最大:32
    session_long: 604800 #単位:秒 60x60x24x7=604800=1週間
    presentation_data_limit: 3600 #単位:秒 60x60=3600=1時間
